baseURL = "/"
languageCode = "en-uk"
title = "Brisbane Open Research Network"
theme = "timer-hugo"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    #[[menu.nav]]
    #    name    = "Service"
    #    url     = "/service"
    #    weight  = 3
    #[[menu.nav]]
    #    name    = "Gallery"
    #    url     = "/gallery"
    #    weight  = 4
    [[menu.nav]]
        name    = "Articles"
        url     = "/blog"
        weight  = 3
    #[[menu.nav]]
    #    name    = "Contact"
    #    url     = "/contact"
    #    weight  = 4

# Site Params
[params]
    home = "Home"
    logo = "images/ferris-wheel.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/bg.jpg"
        heading = "WELCOME TO THE BRISBANE OPEN RESEARCH NETWORK"
        description = "A hub for Open Research practitioners in Brisbane, Australia."
        #btn     = true
        #btnText = "Download More"
        #btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "COMMUNITY"
        [[params.banner.flipText]]
            title   = "ADVOCACY"
        [[params.banner.flipText]]
            title   = "EDUCATION"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT THE NETWORK"
        content = "Open science and open research practices are growing in Australia, but discovering Open research can feel like an isolating experience. This is a mechanism to promote open science and open practices in Queensland, to build a sense of community amongst people who might otherwise feel like the only open researchers they know. <br>We aim to help you find like-minded folks, support efforts to reform institutional policies and practices, and educate others about open research.</br>Follow our <a href='https://groups.google.com/forum/#!forum/bris-open-research'> mailing list</a> or <a href='https://twitter.com/BrisOpenRes'>twitter account</a> for updates.</br></br>Born is an inclusive and welcoming community by design, to preserve this, Born activities are subject to our <a href='https://born.netlify.com/coc'>Code of conduct</a>. Please familiarise yourself with it. "
        image   = "images/about/ferris-wheel.png"

    # Call to Action
    [params.cta]
        enable  = false
        title   = "Do you want to know more?"
        content = "Get in touch and help us grow this community further.</br>You might not be the only person in your institute, let us know so we can start linking you with people in your area."
        btnText = "Contact us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "LOCAL COMMUNITIES"
        subtitle= "Want to find some open science advocates near you? Check out some of our institutional communities."

    # Feature Product Section
    [params.feature]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
